name: Version Increment Check
on:
  pull_request:
    branches: [ main ] # or master, depending on your default branch

jobs:
  version-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # Ensures history is available for comparison

      - name: Fetch main
        run: git fetch origin main:main

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '19' # Use the Node.js version that matches your project requirements

      - run: npm ci

      - name: Run Mutator Tests
        run: npx mocha -r ts-node/register ./client/src/test/mutator.tests.ts

      - name: Check Version Increment
        run: node .github/scripts/version-check.js
        
